apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-collector
  namespace: clustershift
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-reader
rules:
  # Metrics API access
  - apiGroups:
      - "metrics.k8s.io"
    resources:
      - "nodes"
      - "pods"
    verbs:
      - "get"
      - "list"
      - "watch"
  # Core API access
  - apiGroups:
      - ""
    resources:
      - "nodes"
      - "pods"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metrics-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metrics-reader
subjects:
  - kind: ServiceAccount
    name: metrics-collector
    namespace: clustershift
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  namespace: clustershift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-collector
  template:
    metadata:
      labels:
        app: metrics-collector
    spec:
      serviceAccountName: metrics-collector
      containers:
        - name: metrics-collector
          image: ghcr.io/romankudravcev/k8s-metrics-collector:latest
          ports:
            - containerPort: 8089
          volumeMounts:
            - name: sqlite-storage
              mountPath: /app/data
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-collector
  namespace: clustershift
spec:
  selector:
    app: metrics-collector
  ports:
    - port: 80
      targetPort: 8089
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
  namespace: clustershift
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: metrics-collector-route
  namespace: clustershift
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/metrics`)
      kind: Rule
      services:
        - name: metrics-collector
          port: 80
